export const calorieAdvices = [
  'Kalori rendah banget nih, tambah makanan bergizi biar nggak lemes! 🥗✨',
  'Kalori Anda pas, mantap! Pertahankan ya. 😊👍',
  'Kalori agak tinggi, yuk kurangi gorengan dan jalan santai dulu. 🚶‍♂️💪',
  'Kalori super tinggi! Skip dessert dulu, ya. 🍰❌',
  'Tambah serat kayak sayur biar kenyangnya tahan lama. 🥕💕',
  'Seimbangkan kalori dengan gerak cantik tiap hari. 🕺✨',
  'Kalori oke, tapi hati-hati sama camilan manis. 🍬🤭',
  'Coba lemak sehat kayak alpukat atau ikan, biar makin strong! 🥑🐟',
  'Kurangi olahan tinggi kalori, pilih yang alami aja. 🍅✅',
  'Makan lebih banyak buah dan sayur, yuk! 🍏🥗',
  'Jangan lupa olahraga ringan, biar badan makin happy. 🎽😊',
  'Pilih karbo kompleks kayak nasi merah. Energi tahan lama! 🍚💡',
  'Minum air yang cukup ya, kadang lapar itu haus! 🥤😄',
  'Protein berkualitas itu penting, coba ayam atau ikan. 🐔🐟',
  'Jaga porsi makan, biar nggak “drama” sama kalori. 🍜😅',
  'Oatmeal itu keren, bikin kenyang lama dan sehat. 🥣✨',
  'Makan dikit tapi sering, biar energi stabil. 🍴🌟',
  'Makan di tempat tenang bikin lebih mindful dan happy. 🎶🍽️',
  'Kalori tinggi? Porsi kecilin dulu makanan berminyak. 🍟🙅‍♀️',
  'Camilan sehat kayak kacang? Yes banget buat kalori aman. 🥜✨',
];
